---
title: "Exploring_Data"
output: html_document
---

```{r}
library(CASdatasets)
data("auscathist")
aus_data = auscathist
head(aus_data)
```

```{r}
summary(aus_data)
```

```{r}
colnames(aus_data)
dim(aus_data)
```

```{r}
sapply(aus_data,function(x) sum(is.na(x)))
```

```{r}
library(Amelia)
missmap(aus_data, main = "Missing values vs observed")
```

```{r}
aus_data$LastDay = NULL
n = ncol(aus_data)
for(i in 1:n){
  aus_data = subset(aus_data, !is.na(aus_data[,i]))
}
dim(aus_data)
```

```{r}
library(Amelia)
missmap(aus_data, main = "Missing values vs observed")
```


```{r}
summary(aus_data)
```

```{r}
str(aus_data)
```


Suppression des lignes ne contenant pas de locations + rajout des states 
```{r}
aus_data_states = read.csv2("~/3A/cours/Assurance_Non_Vie/Australian_Natural_Catastrophes/data/aus_data.csv", sep = ",")
```


```{r}
str(aus_data_states)
```

```{r}
aus_data_states$Quarter = factor(aus_data_states$Quarter)

```

```{r}
aus_data_states$OriginalCost = as.numeric(aus_data_states$OriginalCost)
```




```{r}
summary(aus_data_states)
```

```{r}
write.csv(aus_data_states, file = "~/3A/cours/Assurance_Non_Vie/Australian_Natural_Catastrophes/data/aus_data_states.csv")
```

